services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  #  generate_csv_source_files:
  #    build:
  #      context: .
  #      dockerfile: src/scripts/csv_generator/Dockerfile
  #    volumes:
  #      - ./src:/src
  #    working_dir: /
  #    command: [ "python", "src/scripts/csv_generator/generate_csv_source_files.py" ]
  #    depends_on:
  #      - minio

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  minio_watcher:
    build:
      context: .
      dockerfile: src/scripts/minio_watcher/Dockerfile
    volumes:
      - ./src:/src
    working_dir: /
    command: [ "python", "src/scripts/minio_watcher/minio_watcher.py" ]
    depends_on:
      - minio
      - kafka
      - zookeeper

volumes:
  minio_data: